version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "33065:3306"
    volumes:
      - dispatcher-data:/var/lib/mysql
    env_file:
      - db.env
  web:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/dispatcher
    ports:
      - "3000:3000"
    env_file:
      - web.env

volumes:
  dispatcher-data:

networks:
  default:
    name: musalasoft-drones
